
  CREATE TABLE SYS.TKPROF_TABLE2 
   (	"DATE_OF_INSERT" DATE, 
	"CURSOR_NUM" NUMBER, 
	"DEPTH" NUMBER, 
	"USER_ID" NUMBER, 
	"PARSE_CNT" NUMBER, 
	"PARSE_CPU" NUMBER, 
	"PARSE_ELAP" NUMBER, 
	"PARSE_DISK" NUMBER, 
	"PARSE_QUERY" NUMBER, 
	"PARSE_CURRENT" NUMBER, 
	"PARSE_MISS" NUMBER, 
	"EXE_COUNT" NUMBER, 
	"EXE_CPU" NUMBER, 
	"EXE_ELAP" NUMBER, 
	"EXE_DISK" NUMBER, 
	"EXE_QUERY" NUMBER, 
	"EXE_CURRENT" NUMBER, 
	"EXE_MISS" NUMBER, 
	"EXE_ROWS" NUMBER, 
	"FETCH_COUNT" NUMBER, 
	"FETCH_CPU" NUMBER, 
	"FETCH_ELAP" NUMBER, 
	"FETCH_DISK" NUMBER, 
	"FETCH_QUERY" NUMBER, 
	"FETCH_CURRENT" NUMBER, 
	"FETCH_ROWS" NUMBER, 
	"TICKS" NUMBER, 
	"SQL_STATEMENT" CLOB, 
	"HANSENSTEP" NUMBER, 
	"HASNENSTEPDESC" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("SQL_STATEMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;